name: Workflow
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:

      - name: "Clone binder"
        uses: actions/checkout@v2

      - name: "Create env"
        uses: mamba-org/setup-micromamba@v2
        with:
            environment-file: test/environment.yml
            init-shell: bash powershell
            cache-environment: true

      - name: "Install binder"
        shell: pwsh
        run: python setup.py install

      - name: "Test binder"
        shell: pwsh
        run: cd test && python -m unittest discover
